# Generated by Django 5.0.3 on 2024-03-23 20:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stations', '0001_initial'),
        ('Trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stations.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trains.train')),
            ],
        ),
    ]
