# Generated by Django 5.0.3 on 2024-04-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedules', '0002_remove_trainschedule_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainschedule',
            name='has_departed',
            field=models.BooleanField(default=False),
        ),
    ]
