# Generated by Django 5.0.3 on 2024-03-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('economy_class_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_class_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
