# Generated by Django 5.0.3 on 2024-04-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trains', '0002_rename_business_class_price_train_businessclassprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='type',
        ),
        migrations.AddField(
            model_name='train',
            name='class_type',
            field=models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='train',
            name='businessClassPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='economyClassPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
