# Generated by Django 5.0.3 on 2024-04-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trains', '0003_remove_train_type_train_class_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='class_type',
            field=models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business')], default='Economy', max_length=20),
        ),
    ]
