# Generated by Django 5.0.3 on 2024-04-13 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trains', '0006_alter_train_businessclassprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='class_type',
        ),
    ]
