# Generated by Django 5.0.3 on 2024-04-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trains', '0007_remove_train_class_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='class_type',
            field=models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business')], default='Economy', max_length=20),
        ),
    ]
