# Generated by Django 5.0.3 on 2024-04-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trains', '0008_train_class_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='class_type',
        ),
        migrations.AlterField(
            model_name='train',
            name='businessClassPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='train',
            name='economyClassPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
