# Generated by Django 5.0.3 on 2024-04-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trains', '0009_remove_train_class_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='capacity',
        ),
        migrations.AddField(
            model_name='train',
            name='business_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='train',
            name='economy_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
