# Generated by Django 5.0.3 on 2024-04-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
