# Generated by Django 5.0.3 on 2024-03-23 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
        ('Stations', '0001_initial'),
        ('UserManagement', '0002_user_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='class_type',
            new_name='classType',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='journey_date',
            new_name='journeyDate',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='destination_station',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='source_station',
        ),
        migrations.AddField(
            model_name='ticket',
            name='destinationStation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='destination_tickets', to='Stations.station'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sourceStation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='source_tickets', to='Stations.station'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.user'),
        ),
    ]
