# Generated by Django 5.0.3 on 2024-04-08 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_rename_class_type_ticket_classtype_and_more'),
        ('UserManagement', '0003_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.passenger'),
        ),
    ]
